### ISSUE TITLE
Various errors installing

### ISSUE THREAD

**Issue by ghost** [zetapath/80cents#2]
Hi guys,

I'm trying to install 80cents on a Ubuntu 14LTS and I have serveral error during the node 80cents.js, this is the output of my temrminal:

azureuser@80cents:~/80cents$ gulp init
[13:43:49] No gulpfile found
azureuser@80cents:~/80cents$ ls
80cents.js  80cents.yml  assets  bower_components  bower.json  environment  gulpfile.coffee  __MACOSX  mustaches  node_modules  package.json  theme
azureuser@80cents:~/80cents$ gulp gulpfile.coffee
[13:44:01] No gulpfile found
# azureuser@80cents:~/80cents$ node 80cents.js

 ZENserver v1.4.18 - Easy (but powerful) NodeJS server
#  https://github.com/soyjavi/zen-server

 ▣ ENVIRONMENT
 ✓ Environment development
 ✓ Address localhost:1337
 ✓ Timezone Europe/Amsterdam
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
## js-bson: Failed to load c++ bson extension, using pure JS version

 ▣ SERVICES
 ✓ [POS] /api/signup
 ✓ [POS] /api/login
 ✓ [POS] /api/logout
 ✓ [GET] /api/profile
 ✓ [PUT] /api/profile
 ✓ [POS] /api/order/line
 ✓ [DEL] /api/order/line
 ✓ [PUT] /api/order/discount
 ✓ [PUT] /api/order
 ✓ [GET] /api/order
 ✓ [GET] /api/customer
 ✓ [PUT] /api/customer
 ✓ [GET] /api/collection
 ✓ [POS] /api/collection
 ✓ [PUT] /api/collection
 ✓ [DEL] /api/collection
 ✓ [GET] /api/product
 ✓ [POS] /api/product
 ✓ [PUT] /api/product
 ✓ [DEL] /api/product
 ✓ [GET] /api/review
 ✓ [POS] /api/review
 ✓ [PUT] /api/review
 ✓ [DEL] /api/review
 ✓ [POS] /api/image
 ✓ [DEL] /api/image
 ✓ [GET] /api/settings
 ✓ [PUT] /api/settings
 ✓ [GET] /api/page
 ✓ [POS] /api/page
 ✓ [PUT] /api/page
 ✓ [DEL] /api/page
 ✓ [GET] /api/discount
 ✓ [POS] /api/discount
 ✓ [PUT] /api/discount
 ✓ [DEL] /api/discount
 ✓ [PUT] /api/order/checkout
 ✓ [GET] /admin/:context/:id
 ✓ [GET] /admin/logout
 ✓ [GET] /admin/:context
 ✓ [GET] /admin
 ✓ [GET] /cart
 ✓ [GET] /order/:id
 ✓ [GET] /checkout
 ✓ [GET] /login
 ✓ [GET] /logout
 ✓ [GET] /profile
 ✓ [POS] /profile
 ✓ [GET] /collection/:id
 ✓ [GET] /product/:id
 ✓ [GET] /tag/:id
 ✓ [GET] /:page
 ✓ [GET] /assets/core
 ⚑ Error connection: undefined
azureuser@80cents:~/80cents$

**Comment by soyjavi** [comment]
2 errors:

No gulpfile and no mongodb connection

**Comment by royalgarter** [comment]
Same problem here. 

Enviroment:
-Window 10
-bower, gulp installed global

**Comment by royalgarter** [comment]
I'm currently using mongolab sandbox as mongodb. So how could I setup the usernam/password in development.yml

**Comment by chrisformula** [comment]
I am getting the following error:

module.js:338
    throw err;
    ^

Error: Cannot find module 'C:\Users{user}\Documents\GitHub\80cents\80cents.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)

What am I missing or doing wrong?
